### ISSUE TITLE
Problem linking github

### ISSUE THREAD

**Issue by ashtastic** [ashtastic/responsive-infographic#2]
@thomasjbradley

Hey Thomas,

All of a sudden my commits weren't showing up on the github app. And so, all the background bars I have put in up to date don't show up when you click on the link in the repository settings... what could this be? Can I still work on it and show you on monday?

**Comment by thomasjbradley** [comment]
My initial thought would be that the folders changed somehow.

Inside the GitHub app go to the menu: `Repository > Reveal in Finder` and see what folder GitHub is looking at.

**Comment by ashtastic** [comment]
That was it! Fixed it. Thank you!
